import type {
  Authenticity,
  PaymentMethod,
  ProductCondition,
  WarrantyType,
} from "../../src/generated/prisma/enums";

/**
 * Vendedores y productos de DEMOSTRACIÓN (solo desarrollo). Sus perfiles lo dicen explícitamente.
 * Los precios y costos están en pesos; el seed los convierte a centavos.
 */
export type ProductSeed = {
  slug: string;
  title: string;
  description: string;
  price: number;
  cost: number;
  stock: number;
  categorySlug: string;
  communitySlug: string;
  condition: ProductCondition;
  authenticity: Authenticity;
  warrantyType: WarrantyType;
  warrantyDays?: number;
  returnWindowDays: number;
  pickupAvailable: boolean;
  localDeliveryZones: string[];
  nationalShipping?: { price: number; minDays: number; maxDays: number };
  tags: string[];
  postBody: string;
};

export type SellerSeed = {
  key: string;
  username: string;
  displayName: string;
  city: string;
  state: string;
  paymentMethods: PaymentMethod[];
  products: ProductSeed[];
};

export const demoSellers: SellerSeed[] = [
  {
    key: "electro",
    username: "demo.electro",
    displayName: "Electro Demo CDMX",
    city: "Ciudad de México",
    state: "CDMX",
    paymentMethods: ["CARD", "TRANSFER", "CASH_ON_DELIVERY"],
    products: [
      {
        slug: "airpods-pro-2-demo",
        title: "AirPods Pro 2",
        description:
          "Audífonos inalámbricos con cancelación activa de ruido, modo ambiente y estuche de carga. Nuevos y sellados.",
        price: 3499,
        cost: 2400,
        stock: 50,
        categorySlug: "audio",
        communitySlug: "tecnologia",
        condition: "NEW",
        authenticity: "DECLARED_ORIGINAL",
        warrantyType: "SELLER",
        warrantyDays: 90,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Benito Juárez", "Coyoacán", "Cuauhtémoc", "Miguel Hidalgo"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["audífonos", "inalámbricos", "cancelación de ruido"],
        postBody:
          "Silencio total en el metro 🎧 AirPods Pro 2 nuevos, con entrega en CDMX o envío a todo México.",
      },
      {
        slug: "control-inalambrico-demo",
        title: "Control inalámbrico para consola y PC",
        description:
          "Control Bluetooth con vibración, batería recargable de 20 horas y compatibilidad con PC y consolas.",
        price: 1199,
        cost: 780,
        stock: 20,
        categorySlug: "accesorios-gaming",
        communitySlug: "gaming",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 60,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Benito Juárez", "Coyoacán"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["control", "gaming", "bluetooth"],
        postBody:
          "Para las retas del fin 🎮 Control inalámbrico con 20 h de batería. ¿Quién se apunta?",
      },
      {
        slug: "cargador-usb-c-30w-demo",
        title: "Cargador rápido USB-C 30 W",
        description:
          "Cargador compacto de carga rápida para celulares y tabletas. Incluye cable USB-C de 1 m.",
        price: 349,
        cost: 150,
        stock: 120,
        categorySlug: "celulares",
        communitySlug: "tecnologia",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 30,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Benito Juárez", "Cuauhtémoc"],
        nationalShipping: { price: 0, minDays: 3, maxDays: 6 },
        tags: ["cargador", "usb-c", "carga rápida"],
        postBody: "Del 0 al 50 % en media hora ⚡ Cargador USB-C de 30 W con envío gratis.",
      },
      {
        slug: "teclado-mecanico-compacto-demo",
        title: "Teclado mecánico compacto 65 %",
        description:
          "Teclado mecánico con switches rojos, retroiluminación RGB y conexión USB-C. Distribución en español.",
        price: 1299,
        cost: 820,
        stock: 15,
        categorySlug: "computacion",
        communitySlug: "gaming",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 90,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: [],
        nationalShipping: { price: 129, minDays: 3, maxDays: 6 },
        tags: ["teclado", "mecánico", "rgb"],
        postBody:
          "Ese clic-clac que te hace escribir más rápido ⌨️ Teclado mecánico compacto 65 %.",
      },
    ],
  },
  {
    key: "casa",
    username: "demo.casa",
    displayName: "Casa y Estilo Demo",
    city: "Guadalajara",
    state: "Jalisco",
    paymentMethods: ["CARD", "TRANSFER", "OXXO"],
    products: [
      {
        slug: "tenis-running-ligeros-demo",
        title: "Tenis para correr ultraligeros",
        description:
          "Tenis de running con suela amortiguada y malla transpirable. Tallas 23 a 29. Ideales para tu primera carrera.",
        price: 1499,
        cost: 900,
        stock: 30,
        categorySlug: "tenis",
        communitySlug: "deportes",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 15,
        pickupAvailable: false,
        localDeliveryZones: ["Zapopan", "Guadalajara Centro"],
        nationalShipping: { price: 149, minDays: 3, maxDays: 7 },
        tags: ["tenis", "running", "deporte"],
        postBody: "Tus primeros 5 km merecen buenos tenis 🏃 Ultraligeros y con amortiguación.",
      },
      {
        slug: "prensa-francesa-1l-demo",
        title: "Prensa francesa de 1 L",
        description:
          "Cafetera de émbolo de vidrio borosilicato y acero inoxidable. Rinde 8 tazas. Fácil de limpiar.",
        price: 459,
        cost: 230,
        stock: 40,
        categorySlug: "cocina",
        communitySlug: "hogar",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 30,
        returnWindowDays: 15,
        pickupAvailable: true,
        localDeliveryZones: ["Zapopan", "Tlaquepaque"],
        nationalShipping: { price: 119, minDays: 3, maxDays: 7 },
        tags: ["café", "cocina", "cafetera"],
        postBody: "El café de la mañana, pero mejor ☕ Prensa francesa de 1 litro.",
      },
      {
        slug: "maceta-barro-pintada-demo",
        title: "Maceta de barro pintada a mano",
        description:
          "Maceta de barro de Tonalá pintada a mano, 15 cm de diámetro. Cada pieza es única.",
        price: 289,
        cost: 120,
        stock: 25,
        categorySlug: "hecho-a-mano",
        communitySlug: "hogar",
        condition: "NEW",
        authenticity: "NOT_APPLICABLE",
        warrantyType: "NONE",
        returnWindowDays: 0,
        pickupAvailable: true,
        localDeliveryZones: ["Tonalá", "Guadalajara Centro"],
        nationalShipping: { price: 99, minDays: 4, maxDays: 8 },
        tags: ["artesanía", "plantas", "barro"],
        postBody: "Hecha a mano en Tonalá 🌱 Cada maceta es única, como tus plantas.",
      },
      {
        slug: "correa-retractil-5m-demo",
        title: "Correa retráctil para perro de 5 m",
        description:
          "Correa retráctil con freno de un toque y mango antiderrapante. Para perros de hasta 25 kg.",
        price: 329,
        cost: 160,
        stock: 35,
        categorySlug: "mascotas",
        communitySlug: "mascotas",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 30,
        returnWindowDays: 7,
        pickupAvailable: false,
        localDeliveryZones: ["Zapopan"],
        nationalShipping: { price: 99, minDays: 3, maxDays: 7 },
        tags: ["perros", "paseo", "correa"],
        postBody: "Paseos más tranquilos 🐕 Correa retráctil de 5 m con freno de un toque.",
      },
    ],
  },
  {
    key: "moda",
    username: "demo.moda",
    displayName: "Ropero Demo Roma",
    city: "Ciudad de México",
    state: "CDMX",
    paymentMethods: ["CARD", "TRANSFER", "CASH_ON_DELIVERY"],
    products: [
      {
        slug: "camisa-blanca-vestir-demo",
        title: "Camisa blanca de vestir slim",
        description:
          "Camisa de algodón con corte slim y cuello italiano. Sirve para la oficina, una entrevista o una boda de día con saco.",
        price: 649,
        cost: 320,
        stock: 18,
        categorySlug: "camisas-y-blusas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc", "Benito Juárez"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["camisa", "formal", "vestir", "blanco", "algodón"],
        postBody:
          "La camisa blanca que combina con todo 👔 Corte slim, cuello italiano y algodón fresco.",
      },
      {
        slug: "playera-polo-blanca-demo",
        title: "Playera polo blanca de algodón",
        description: "Polo de piqué de algodón, corte regular. Casual y fresca para el día a día.",
        price: 399,
        cost: 190,
        stock: 30,
        categorySlug: "camisas-y-blusas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["polo", "casual", "algodón", "blanco", "básico"],
        postBody: "Polo blanca de piqué: el básico casual que no falla 🤍",
      },
      {
        slug: "blusa-negra-satinada-demo",
        title: "Blusa negra satinada sin mangas",
        description:
          "Blusa satinada de caída ligera, ideal para la noche o para combinar con saco en la oficina.",
        price: 549,
        cost: 260,
        stock: 12,
        categorySlug: "camisas-y-blusas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["blusa", "elegante", "noche", "negro", "satín"],
        postBody: "Blusa negra satinada: de la oficina a la cena sin cambiarte 🖤",
      },
      {
        slug: "jeans-rectos-azul-demo",
        title: "Jeans rectos azul claro",
        description: "Jeans de mezclilla rígida con corte recto y tiro medio. Tallas 26 a 34.",
        price: 799,
        cost: 380,
        stock: 22,
        categorySlug: "pantalones-y-faldas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc", "Benito Juárez"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["jeans", "mezclilla", "casual", "azul", "recto"],
        postBody: "Jeans rectos azul claro, mezclilla rígida de la buena 👖",
      },
      {
        slug: "pantalon-vestir-negro-demo",
        title: "Pantalón de vestir negro slim",
        description:
          "Pantalón de vestir con corte slim y tela con un poco de elastano. Para entrevistas, oficina y eventos.",
        price: 899,
        cost: 430,
        stock: 16,
        categorySlug: "pantalones-y-faldas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["pantalón", "formal", "vestir", "negro", "slim"],
        postBody: "Pantalón de vestir negro slim: el que te saca de cualquier evento.",
      },
      {
        slug: "vestido-blanco-encaje-demo",
        title: "Vestido blanco de encaje sin mangas",
        description:
          "Vestido de encaje floral con forro, largo a la rodilla. Para una boda de día, una graduación o una cita.",
        price: 1299,
        cost: 620,
        stock: 8,
        categorySlug: "vestidos",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["vestido", "encaje", "elegante", "blanco", "boda"],
        postBody: "Vestido blanco de encaje: ligero, elegante y listo para una boda de día 🤍",
      },
      {
        slug: "saco-negro-entallado-demo",
        title: "Saco negro entallado",
        description:
          "Saco de dos botones con corte entallado y forro completo. Combina con camisa y pantalón de vestir o con jeans.",
        price: 1499,
        cost: 720,
        stock: 10,
        categorySlug: "chamarras-y-sacos",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "NONE",
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc", "Benito Juárez"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["saco", "blazer", "formal", "elegante", "negro"],
        postBody:
          "Saco negro entallado: con jeans se ve moderno, con pantalón de vestir, impecable.",
      },
      {
        slug: "tenis-blancos-minimal-demo",
        title: "Tenis blancos minimalistas",
        description:
          "Tenis de piel sintética blanca con suela de goma. Limpios y versátiles; van con jeans, shorts o pantalón de vestir.",
        price: 1099,
        cost: 520,
        stock: 20,
        categorySlug: "tenis",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 30,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc", "Benito Juárez"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["tenis", "sneaker", "blanco", "casual", "moderno", "minimal"],
        postBody: "Tenis blancos minimal: los que van con todo lo que tienes en el ropero 👟",
      },
      {
        slug: "zapatos-piel-cafe-demo",
        title: "Zapatos de piel café de vestir",
        description:
          "Zapatos de piel con suela cosida y punta redonda. Para traje, boda o entrevista.",
        price: 1599,
        cost: 780,
        stock: 9,
        categorySlug: "tenis",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 60,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa"],
        nationalShipping: { price: 129, minDays: 2, maxDays: 5 },
        tags: ["zapatos", "formal", "vestir", "piel", "café", "elegante"],
        postBody: "Zapatos de piel café: los de vestir que sí aguantan el día entero 👞",
      },
      {
        slug: "bolsa-piel-cafe-demo",
        title: "Bolsa de piel café con asa",
        description:
          "Bolsa de piel curtida con asa corta y cierre. Cabe una tableta de 11 pulgadas.",
        price: 1199,
        cost: 560,
        stock: 7,
        categorySlug: "bolsas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 90,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["bolsa", "piel", "café", "elegante", "clásico"],
        postBody: "Bolsa de piel café, hecha para durar y para combinar con todo 👜",
      },
      {
        slug: "bolsa-negra-piel-demo",
        title: "Bolsa negra de piel cruzada",
        description:
          "Bolsa cruzada de piel negra con correa ajustable. Ligera, para salir de noche.",
        price: 899,
        cost: 410,
        stock: 11,
        categorySlug: "bolsas",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 90,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["bolsa", "piel", "negro", "noche", "moderno"],
        postBody: "Bolsa negra cruzada: manos libres y lista para la noche 🖤",
      },
      {
        slug: "reloj-correa-cuero-demo",
        title: "Reloj con correa de cuero café",
        description:
          "Reloj de cuarzo con carátula plateada y correa de cuero café. Clásico, para la oficina o un evento.",
        price: 899,
        cost: 420,
        stock: 14,
        categorySlug: "relojes-y-joyeria",
        communitySlug: "moda",
        condition: "NEW",
        authenticity: "GENERIC",
        warrantyType: "SELLER",
        warrantyDays: 180,
        returnWindowDays: 7,
        pickupAvailable: true,
        localDeliveryZones: ["Roma", "Condesa", "Cuauhtémoc", "Benito Juárez"],
        nationalShipping: { price: 99, minDays: 2, maxDays: 5 },
        tags: ["reloj", "clásico", "cuero", "café", "elegante"],
        postBody: "Reloj con correa de cuero: el detalle clásico que completa el look ⌚",
      },
    ],
  },
];
